repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: uv run black
        language: system
        types: [python]

      - id: isort
        name: isort
        entry: uv run isort
        language: system
        types: [python]
