services:
  backend:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./static/image/photo/:/app/static/image/photo/
      - ./download/:/app/download/
      - ./db/:/app/db/
    entrypoint: bash
    command: >
      -c '
      echo "Checking DB at /app/${SQLITE_FILENAME}";

      if [ ! -f "/app/${SQLITE_FILENAME}" ]; then
        echo "Database not found. Initializing...";
        chmod +x ./script/*.sh &&
        ./script/init_db.sh "/app/${SQLITE_FILENAME}" &&
        ./script/insert_scsc_global_status.sh "/app/${SQLITE_FILENAME}" &&
        ./script/insert_user_roles.sh "/app/${SQLITE_FILENAME}" &&
        ./script/insert_majors.sh "/app/${SQLITE_FILENAME}" ./docs/majors.csv;
      else
        echo "Database already exists. Skipping initialization.";
      fi;

      exec fastapi run main.py --host 0.0.0.0 --port 8080
      '
