name: scsc_init_backend
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.12.9
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.9.0
      - attrs==25.3.0
      - certifi==2025.4.26
      - click==8.1.8
      - discord-py==2.5.2
      - dnspython==2.7.0
      - email-validator==2.2.0
      - fastapi==0.115.12
      - fastapi-cli==0.0.7
      - frozenlist==1.7.0
      - greenlet==3.2.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - idna==3.10
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - multidict==6.4.4
      - propcache==0.3.2
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pydantic-settings==2.9.1
      - pygments==2.19.1
      - pyjwt==2.10.1
      - python-dotenv==1.1.0
      - python-multipart==0.0.20
      - pyyaml==6.0.2
      - rich==14.0.0
      - rich-toolkit==0.14.5
      - shellingham==1.5.4
      - sniffio==1.3.1
      - sqlalchemy==2.0.40
      - sqlmodel==0.0.24
      - starlette==0.46.2
      - typer==0.15.3
      - typing-extensions==4.13.2
      - typing-inspection==0.4.0
      - uvicorn==0.34.2
      - uvloop==0.21.0
      - watchfiles==1.0.5
      - websockets==15.0.1
      - yarl==1.20.1
