CREATE TABLE user_activity_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    activity_type TEXT NOT NULL,
    created_by TEXT DEFAULT NULL,
    detail TEXT DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_user_activity_log_user
        FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE RESTRICT,

    CONSTRAINT fk_user_activity_log_created_by
        FOREIGN KEY (created_by) REFERENCES "user"(id) ON DELETE RESTRICT,

    CONSTRAINT chk_user_activity_log_activity_type
        CHECK (
            activity_type IN (
                'SIGNED_UP',
                'REGISTERED',
                'SIG_JOINED',
                'SIG_LEFT',
                'SIG_LEADER_APPOINTED'
            )
        )
);

CREATE INDEX idx_user_activity_log_user_id
    ON user_activity_log(user_id);

CREATE INDEX idx_user_activity_log_created_at
    ON user_activity_log(created_at);

CREATE INDEX idx_user_activity_log_activity_type
    ON user_activity_log(activity_type);