INSERT INTO public.user_role (level, name, kor_name)
VALUES (350, 'external', '외부회원');

ALTER TABLE public."user"
    ALTER COLUMN student_id DROP NOT NULL,
    ALTER COLUMN major_id DROP NOT NULL;

CREATE TABLE external_member_application (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    student_id TEXT DEFAULT NULL,
    reason TEXT DEFAULT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    reviewed_by TEXT DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_external_member_application_reviewer
        FOREIGN KEY (reviewed_by) REFERENCES "user"(id) ON DELETE SET NULL,

    CONSTRAINT chk_external_member_application_status
        CHECK (status IN ('pending', 'approved', 'rejected'))
);
